version: "1.0"
info:
  scaffold: testFS
  model: int-scaffold
services:
- serviceName: pub.string:toUpper
  packages:
  - name: WmPublic
    version: 11.0.0.0.248
- serviceName: edge.vidiapril7.integrations:testFS
  packages:
  - name: EdgeVidiApril7
    version: "1.0"
